In [5]:
import numpy as np
import math

In [4]:
math.comb(6, 3)


20

$2^{n-k}\geq \sum_{i=0}^t C_n^i$


In [9]:
G = np.array([
    [0, 0, 0, 0, 1, 1, 1, 1],
    [1, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0,],
    [0, 0, 1, 1, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 0, 0, 0, 0, 1, 1]
])

In [11]:
np.linalg.matrix_rank(G)

4

In [8]:
len((1,0,0,0,28,0,0,0,70,0,0,0,0,28,0,0,1)

)

17

In [12]:
Gt = G.transpose()

In [13]:
Gt

array([[0, 1, 1, 0, 0, 0, 1, 1],
       [0, 1, 1, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 0, 1, 1, 0],
       [1, 0, 1, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 1],
       [1, 0, 0, 1, 0, 0, 1, 1]])

In [14]:
np.linalg.matrix_rank(Gt)

4

In [15]:
def bound(n, t, i):
    return 2**n / (sum([math.comb(n, i) for i in range(0, t + 1)]))

In [16]:
k =
d = 4

SyntaxError: invalid syntax (3448459993.py, line 1)

In [17]:
G = np.array([
    [1, 1, 1, 1, 1, 1, 1, 1,],
    [1, 1, 1, 1, 0, 0, 0, 0,],
    [1, 1, 0, 0, 1, 1, 0, 0,],
    [1, 0, 1, 0, 1, 0, 1, 0,],
])

In [18]:
G @ np.array([1, 1, 1, 1, 1, 1, 1, 1])

array([8, 4, 4, 4])

In [19]:
G @ G.transpose() # проверяем что сама же G является проверочной для самой себя

array([[8, 4, 4, 4],
       [4, 4, 2, 2],
       [4, 2, 4, 2],
       [4, 2, 2, 4]])