In [12]:
import galois
import numpy as np
import pytest
import ipytest

import utils

ipytest.autoconfig()

%load_ext autoreload
# %reload_ext autoreload
%autoreload 1
%aimport utils

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
# %%ipytest

# @pytest.mark.parametrize(
#     "string,matrix", 
#     [
#         ("000", [[0, 0, 0]]), 
#         ("111 111", [[1, 1, 1], [1, 1, 1]]),
#         ("0\n0\n0", [[0], [0], [0]]),
#         ("01\n 10 \n 01", [[0, 1], [1, 0], [0, 1]]),
#     ]
# )
# def test_string_to_matrix(string: str, matrix: [[int]]) -> None:
#     assert string_to_matrix(string) == matrix

In [34]:

x = galois.GF2(utils.string_to_matrix(
'''
00001111
11110000
11001100                    
00110011
00000000
00111100
11111111
11000011
'''))

In [35]:
# Requirements for a set of vectors to be a linear block code
# 1) Is a linear subspace in GF(2)^n (=> has a neutral element = 0)
# 2) Has a rank of log_2(n)=3

np.linalg.matrix_rank(x)

3

In [36]:
np_x = np.array(utils.string_to_matrix(
'''
00001111
11110000
11001100                    
00110011
00000000
00111100
11111111
11000011
'''))

np.linalg.matrix_rank(np_x)

3

In [17]:
utils.row_echelon_form(x)
utils.is_row_echelon_form(utils.row_echelon_form(x))

True

In [33]:
utils.row_echelon_form(x)


GF([[1, 1, 0, 0, 0, 0, 1, 1],
    [0, 0, 1, 1, 0, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]], order=2)

In [19]:
g_mat = utils.get_generator_matrix(x)
g_mat

GF([[1, 1, 0, 0, 0, 0, 1, 1],
    [0, 0, 1, 1, 0, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 1, 1]], order=2)

In [20]:
utils.get_code_by_generator_matrix(g_mat)

GF([[0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1],
    [0, 0, 1, 1, 0, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 1, 1],
    [1, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 1]], order=2)

# Расчетное задание к 13.10.2023
Необходимо указать длину n, размерность k и минимальное расстояние линейного блокового кода над GF(2) с заданной проверочной матрицей, а также найти его порождающую матрицу. Порождающая матрица должна содержать единичную подматрицу в столбцах с наименьшими возможными номерами.  Кроме того, необходимо выписать таблицу стандартной расстановки для этого кода.  

Порождающая матрица должна быть выписана построчно.  Если размерность кода меньше, чем число строк, матрицу необходимо дополнить нулевыми строками.  Не допускается ввод пробелов, знаков препинания и иных посторонних символов ни в какие поля - это будет засчитано как ошибка. В случае, если одному значению синдрома S соответствуют несколько лидеров смежного класса одного и того же веса, необходимо указать в качестве T[S] вектор, имеющий 1 в самой левой позиции (лексикографически больший).   Например, если вектора 01010  и 10001 имеют один и тот же синдром, следует указать в качестве лидера смежного класса 10001.

Пример оформления порождающей матрицы:

```
10010101
01010011
00110110
00001111
```

In [45]:
x = galois.GF2(utils.string_to_matrix(
'''
1000100001
0100001110
0010100110
0001100111
0000011001
'''
))
x

GF([[1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
    [0, 1, 0, 0, 0, 0, 1, 1, 1, 0],
    [0, 0, 1, 0, 1, 0, 0, 1, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 1, 1, 1],
    [0, 0, 0, 0, 0, 1, 1, 0, 0, 1]], order=2)

In [46]:
g = utils.get_generator_matrix(x)
g

GF([[1, 0, 0, 0, 1, 1, 1, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 1, 1, 1, 0],
    [0, 0, 1, 0, 1, 0, 0, 1, 1, 0],
    [0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
    [0, 0, 0, 0, 0, 1, 1, 0, 0, 1]], order=2)

In [47]:
g.shape  # k, n

(5, 10)

In [48]:
c = utils.get_code_by_generator_matrix(g)
c

GF([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 1, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 1, 1, 1, 0],
    [0, 0, 1, 0, 1, 0, 0, 1, 1, 0],
    [0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
    [0, 0, 0, 0, 0, 1, 1, 0, 0, 1],
    [1, 1, 0, 0, 1, 1, 0, 1, 1, 0],
    [1, 0, 1, 0, 0, 1, 1, 1, 1, 0],
    [1, 0, 0, 1, 0, 0, 0, 1, 1, 0],
    [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
    [0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
    [0, 1, 0, 1, 1, 1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 1, 1, 1],
    [0, 0, 1, 1, 0, 1, 1, 0, 0, 0],
    [0, 0, 1, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 1, 1, 0, 0, 1, 1, 1],
    [1, 1, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 1, 0, 1, 1, 1, 1],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
    [1, 0, 0, 1, 0, 1, 1, 1, 1, 1],
    [0, 1, 1, 1, 0, 1, 0, 1, 1, 0],
    [0, 1, 1, 0, 1, 1, 0, 0, 0, 1],
    [0, 1, 0, 1, 1, 0, 1, 0, 0, 1],
    [0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 0, 1, 1, 1, 0],
    [1, 1, 1, 0, 0, 0, 1, 0,

In [31]:
utils.get_code_minimal_distance(c)

3

В ответе просят сделать так чтобы

In [8]:
g

GF([[1, 0, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]], order=2)

In [32]:
g_final = g.transpose()
g_final

GF([[1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0],
    [1, 0, 1, 1, 0],
    [1, 0, 0, 1, 1],
    [1, 1, 0, 1, 1],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 1]], order=2)

In [11]:
g_final[[4, 9]] = g_final[[9, 4]]
g

GF([[1, 0, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 1, 0, 0, 0]], order=2)

In [14]:
print(utils.matrix_to_string(g))

1000001100
0100010010
0010001001
0001001001
0000101000


In [16]:
np.linalg.matrix_rank(xs)

5

In [19]:
g

GF([[1, 0, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 1, 0, 0, 0]], order=2)

In [20]:
g.transpose()[5:].transpose()

GF([[0, 1, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [0, 1, 0, 0, 1],
    [0, 1, 0, 0, 1],
    [0, 1, 0, 0, 0]], order=2)

In [23]:
h = galois.GF2(utils.string_to_matrix(
    '''
0100010000
1011101000
1000000100
0100000010
0011000001
    '''
))
h

GF([[0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 1, 1, 0, 0, 0, 0, 0, 1]], order=2)

In [26]:
g @ h.transpose()

GF([[0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]], order=2)

GF([[1, 0, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 1, 0, 0, 0]], order=2)

In [29]:
X_eye = galois.GF2(np.eye(10, 10, dtype=int))
X_eye

GF([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], order=2)

In [31]:
X_space = utils.get_code_by_generator_matrix(X_eye)
print(np.linalg.matrix_rank(X_space))
print(len(X_space))
print(X_space)

10
1024
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [1 0 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [41]:
with open("matrix.txt", "w") as f:
    with np.printoptions(threshold=np.inf):
        f.write(str(X_space))
    # f.write(np.sort(X_space, axis=0).str)


In [42]:
X_space_sorted = galois.GF2(utils.string_to_matrix(open("matrix.txt", "r").read()))
X_space_sorted

GF([[0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 1],
    [0, 0, 0, ..., 0, 1, 0],
    ...,
    [1, 1, 1, ..., 1, 0, 1],
    [1, 1, 1, ..., 1, 1, 0],
    [1, 1, 1, ..., 1, 1, 1]], order=2)

In [45]:
def vec_to_string(v: galois.GF2) -> str:
    return ''.join([str(int(x)) for x in v])
vec_to_string(X_space_sorted[16])

'0000010000'

In [46]:
from collections import defaultdict

T = defaultdict(list)
for x in X_space_sorted:
    T[vec_to_string(x @ h.transpose())].append(x)
T

defaultdict(list,
            {'00000': [GF([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], order=2),
              GF([0, 0, 0, 0, 1, 0, 1, 0, 0, 0], order=2),
              GF([0, 0, 0, 1, 0, 0, 1, 0, 0, 1], order=2),
              GF([0, 0, 0, 1, 1, 0, 0, 0, 0, 1], order=2),
              GF([0, 0, 1, 0, 0, 0, 1, 0, 0, 1], order=2),
              GF([0, 0, 1, 0, 1, 0, 0, 0, 0, 1], order=2),
              GF([0, 0, 1, 1, 0, 0, 0, 0, 0, 0], order=2),
              GF([0, 0, 1, 1, 1, 0, 1, 0, 0, 0], order=2),
              GF([0, 1, 0, 0, 0, 1, 0, 0, 1, 0], order=2),
              GF([0, 1, 0, 0, 1, 1, 1, 0, 1, 0], order=2),
              GF([0, 1, 0, 1, 0, 1, 1, 0, 1, 1], order=2),
              GF([0, 1, 0, 1, 1, 1, 0, 0, 1, 1], order=2),
              GF([0, 1, 1, 0, 0, 1, 1, 0, 1, 1], order=2),
              GF([0, 1, 1, 0, 1, 1, 0, 0, 1, 1], order=2),
              GF([0, 1, 1, 1, 0, 1, 0, 0, 1, 0], order=2),
              GF([0, 1, 1, 1, 1, 1, 1, 0, 1, 0], order=2),
              GF([1, 0, 0, 0,

In [55]:
import heapq

T_leaders = {
    k: [vec for vec in v if np.count_nonzero(vec) == min([np.count_nonzero(vec_) for vec_ in v])] for k, v in T.items()
}
T_leaders # answer to the task

{'00000': [GF([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], order=2)],
 '00001': [GF([0, 0, 0, 0, 0, 0, 0, 0, 0, 1], order=2)],
 '00010': [GF([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], order=2)],
 '00011': [GF([0, 0, 0, 0, 0, 0, 0, 0, 1, 1], order=2)],
 '00100': [GF([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], order=2)],
 '00101': [GF([0, 0, 0, 0, 0, 0, 0, 1, 0, 1], order=2),
  GF([1, 0, 0, 1, 0, 0, 0, 0, 0, 0], order=2),
  GF([1, 0, 1, 0, 0, 0, 0, 0, 0, 0], order=2)],
 '00110': [GF([0, 0, 0, 0, 0, 0, 0, 1, 1, 0], order=2)],
 '00111': [GF([0, 0, 0, 0, 0, 0, 0, 1, 1, 1], order=2),
  GF([1, 0, 0, 1, 0, 0, 0, 0, 1, 0], order=2),
  GF([1, 0, 1, 0, 0, 0, 0, 0, 1, 0], order=2)],
 '01000': [GF([0, 0, 0, 0, 0, 0, 1, 0, 0, 0], order=2),
  GF([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], order=2)],
 '01001': [GF([0, 0, 0, 1, 0, 0, 0, 0, 0, 0], order=2),
  GF([0, 0, 1, 0, 0, 0, 0, 0, 0, 0], order=2)],
 '01010': [GF([0, 0, 0, 0, 0, 0, 1, 0, 1, 0], order=2),
  GF([0, 0, 0, 0, 1, 0, 0, 0, 1, 0], order=2)],
 '01011': [GF([0, 0, 0, 1, 0, 0, 0, 0, 1, 0]

In [57]:
{ k : list(map(vec_to_string, v)) for k, v in T_leaders.items() }

{'00000': ['0000000000'],
 '00001': ['0000000001'],
 '00010': ['0000000010'],
 '00011': ['0000000011'],
 '00100': ['0000000100'],
 '00101': ['0000000101', '1001000000', '1010000000'],
 '00110': ['0000000110'],
 '00111': ['0000000111', '1001000010', '1010000010'],
 '01000': ['0000001000', '0000100000'],
 '01001': ['0001000000', '0010000000'],
 '01010': ['0000001010', '0000100010'],
 '01011': ['0001000010', '0010000010'],
 '01100': ['1000000000'],
 '01101': ['0001000100', '0010000100', '1000000001'],
 '01110': ['1000000010'],
 '01111': ['0001000110', '0010000110', '1000000011'],
 '10000': ['0000010000'],
 '10001': ['0000010001'],
 '10010': ['0100000000'],
 '10011': ['0100000001'],
 '10100': ['0000010100'],
 '10101': ['0000010101', '1001010000', '1010010000'],
 '10110': ['0100000100'],
 '10111': ['0100000101', '1101000000', '1110000000'],
 '11000': ['0000011000', '0000110000'],
 '11001': ['0001010000', '0010010000'],
 '11010': ['0100001000', '0100100000'],
 '11011': ['0101000000', '011000

# Блять, все расчеты выше неправильыне
Энивей, приступаем ко второму заданию:

Длина = 19, минимальное расстояние = 8. Оцените максимальную размерность кода, которую допускает граница :
- Хемминга
- Грайсмера
- Варшамова-Гилберта

In [64]:
import math

def get_hamming_bound(n, t):
    denom = sum(math.comb(n, i) for i in range(0, t + 1))
    return (2**n) // denom

get_hamming_bound(19, t=7)

5